### ISSUE TITLE
[FEATURE] 가이드 모드 옵션 컴포넌트 구현

### ISSUE THREAD

**Issue by yen001004** [softeerbootcamp-2nd/A3-OhMyCarSet#145]
## To-Do
- [x] 셀프모드에 구매 비율 추가
- [x] 옵션 컴포넌트 확장
- [x] 가이드 모드 옵션 UI 구현

## up-to-date
8월 20일
