### ISSUE TITLE
[BE/FEATURE] 무중단 배포 적용

### ISSUE THREAD

**Issue by jst0951** [softeerbootcamp-2nd/A3-OhMyCarSet#155]
## To-Do
- [x] 테스트벤치 환경에서 테스트(+ 블로그 글 작성)
- [x] 테스트벤치 환경을 프로덕션 환경으로 승급
- [x] github action 스크립트 수정

### 

### ~금요일 데모 전

**Comment by jst0951** [comment]
중단 시간이 필요하므로 데모 전까지만 진행하는 것으로 수정

**Comment by jst0951** [comment]
작업하면서 #205 역시 진행. 이후 작업 완료.
