### ISSUE TITLE
[BE/FEATURE] 기본 옵션 고화질 이미지 파싱 후 등록

### ISSUE THREAD

**Issue by jst0951** [softeerbootcamp-2nd/A3-OhMyCarSet#187]
## To-Do
- [x] 고화질 이미지 현대 내차만들기에서 파싱
- [x] 모두 webp로 변환
- [x] 사용 가이드 노션 페이지로 등록

###
