### ISSUE TITLE
[BE/FEATURE] 매핑 데이터 현실적으로 변경

### ISSUE THREAD

**Issue by jst0951** [softeerbootcamp-2nd/A3-OhMyCarSet#99]
## To-Do
- [x] purchase_history에서 파워트레인, 구동 방식, 바디 타입, 외장 색상, 내장 색상, 휠, 나이, 성별 분포 수정한 csv파일 제작
- [x] purchase_system_map에서 실구매비율 반영하여 csv파일 제작
- [x] purchase_temperature_map에서 실구매비율 반영하여 csv파일 제작
- [x] purchase_external_device_map에서 실구매비율 반영하여 csv파일 제작
- [x] purchase_internal_device_map에서 실구매비율 반영하여 csv파일 제작
- [x] 제작된 csv파일 라이브 서버에 적용

**Comment by jst0951** [comment]
8/15 작업 완료 및 라이브 서버 적용 완료
